const data = {
 
    products:[
        {   id:1,
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:470,
            countInStock:10,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
              id:2,
            name:'Nike Slim Shirt',
            category:'Shirts',
            image:'/images/p2.jpg',
            countInStock:20,
            price:560,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            id:3,
            name:'Adidas Slim Shirt',
            category:'Shirts',
            image:'/images/p3.jpg',
            countInStock:0,
            price:789,
            brand:'Adidas',
            rating:4.8,
            numReviews:17,
            description:'high quality product',
        },
        {
            id:4,
            name:'Nike Slim Pants',
            category:'Shirts',
            image:'/images/p4.jpg',
            countInStock:5,
            price:450,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            id:5,
            name:'Nike Slim Lower',
            category:'Shirts',
            image:'/images/p5.jpg',
            countInStock:10,
            price:499,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            id:6,
            name:'Nike Slim jokey',
            category:'Shirts',
            image:'/images/p6.jpg',
            price:1120,
            brand:'Nike',
            countInStock:20,    
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
    ]
}
export default data