export const SIGNIN_REQUEST = 'SIGNIN_REQUEST'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'


export const SIGN_OUT = 'SIGN_OUT'



export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL='USER_REGISTER_FAIL'


export const USER_SHIPPING_ADDRESS = 'USER_SHIPPING_ADDRESS'


export const USER_PAYMENT_METHOD = 'USER_PAYMENT_METHOD'


export const USER_UPDATE_REQUEST='USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS='USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL='USER_UPDATE_FAIL'

export const USER_ORDER_REQUEST = 'USER_ORDER_REQUEST'
export const USER_ORDER_SUCCESS = 'USER_ORDER_SUCCESS'
export const USER_ORDER_FAIL = 'USER_ORDER_FAIL'
